on:

  push:
    branches:
    - Germany
jobs:
 pipeline_to_copy:
  runs-on: ubuntu-latest 
  steps:
   - name: Script
     run: git clone git@github.com:teadypicker/FortoTest.git
          cd Germany
          git remote add devops git@github.com:teadypicker/Germany.git
