on:

  push:
    branches:
    - Germany
jobs:
 pipeline_to_copy:
  runs-on: ubuntu-latest 
  steps:
   - name: Script
     run:
        git config --global user.email "ope@global-mediator.com"
        git clone git@github.com:teadypicker/FortoTest.git
        cd Germany
        git remote add devops git@github.com:teadypicker/Germany.git
        git checkout -b main
        git merge Germany
        git fetch devops main
        git merge devops/main 
        git push -u devops main:main
