on:

  push:
    branches:
    - Germany
jobs:
 pipeline_to_copy:
  runs-on: ubuntu-latest 
  steps:
   - name: Script
     run:
         git config --global user.email "ope@global-mediator.com"
         git config --global user.name "Olha Petryk"
